services:
  task_service_db: 
    image: postgres
    ports: 
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_TASKDB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TASK_DB_NAME}
    volumes:
      - task_service_db_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 1s
      retries: 20

  auth_service_db: 
    image: postgres
    ports: 
      - 5433:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_AUTHDB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_AUTH_DB_NAME}
    volumes:
      - auth_service_db_volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 1s
      retries: 20

volumes:
  auth_service_db_volume:
  task_service_db_volume:
